---
title: "Forcasting"
author: "Kassie"
output:
  pdf_document: default
  html_document: default
date: '2023-04-17'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load packages
```{r packages}

library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(kableExtra)
```

## Including Plots
Change the data:
```{r, echo=FALSE}
load("./Data/biomass_Env.RDATA")
full_data <- rawdata_all_fill %>%
  as.data.frame() 

# Transform to time series format
ts_biomass_full <- ts(
  full_data$Biomass,
  start=c(year(full_data$date[1]),month(full_data$date[1])),
  frequency=12) 

ts_temp <- ts(
  full_data$Temperature,
  start=c(year(full_data$date[1]),month(full_data$date[1])),
  frequency=12) 

ts_TN <- ts(
  full_data$TN,
  start=c(year(full_data$date[1]),month(full_data$date[1])),
  frequency=12) 

ts_TP <- ts(
  full_data$TP,
  start=c(year(full_data$date[1]),month(full_data$date[1])),
  frequency=12) 




last_obs <- ts_biomass_data[301:312]
```

*TBD:
transform all the columns into ts

```{r pressure, echo=FALSE}
# Change the time span
# Transform to time series format

ts_biomass_data <- ts(
  biomass_data_frame[181:312,2],
  start=c(year(biomass_data_frame$Month[181]),month(biomass_data_frame$Month[181])),
  frequency=12) 

ts_biomass <- ts(
  biomass_data_frame[181:300,2],
  start=c(year(biomass_data_frame$Month[181]),month(biomass_data_frame$Month[181])),
  frequency=12)


last_obs <- ts_biomass_data[121:132]


# Plot the time series, ACF, and PACF
TS_Plot <- ggplot(biomass_data_frame, aes(x=Month, y=Biomass)) +
      geom_line()

plot(TS_Plot)


#ACF and PACF plots
par(mfrow=c(1,2))
ACF_Plot <- Acf(ts_biomass_data, lag = 40, plot = TRUE,main="")
PACF_Plot <- Pacf(ts_biomass_data, lag = 40, plot = TRUE,main="")




# Forecast using ARIMA (Temporally not used)
#Using R decompose function
decompose_biomass_data <- decompose(ts_biomass,"additive")
deseasonal_biomass_data <- seasadj(decompose_biomass_data) 

ARIMA_autofit <- auto.arima(deseasonal_biomass_data)
summary(ARIMA_autofit)

ARIMA_for <- forecast(ARIMA_autofit,h=12)
plot(ARIMA_for)

new_forcast <- ARIMA_for$mean + decompose_biomass_data$seasonal[1:12]


# Forcast using SARIMA
SARIMA_autofit <- auto.arima(ts_biomass)
summary(SARIMA_autofit)

SARIMA_for <- forecast(SARIMA_autofit,h=12)
plot(SARIMA_for)


# Other models
# Exponential smooth
ES_biomass=es(y = ts_biomass, h = 12, holdout = FALSE, silent = FALSE)
NAIVE_biomass <- naive(deseasonal_biomass_data, h=12)

plot(NAIVE_biomass)
checkresiduals(NAIVE_biomass)

new_forcast_naive <- NAIVE_biomass$mean + decompose_biomass_data$seasonal[1:12]



NAIVE_scores <- accuracy(new_forcast_naive,last_obs) 
ARIMA_scores <- accuracy(new_forcast,last_obs)
SARIMA_scores <- accuracy(SARIMA_for$mean,last_obs)

ES_scores <- accuracy(ES_biomass$forecast,last_obs) 

biomass_scores <- as.data.frame(rbind(NAIVE_scores, ARIMA_scores,SARIMA_scores, ES_scores))
row.names(biomass_scores) <- c("NAIVE", "ARIMA","SARIMA","ES")

kbl(biomass_scores, 
      caption = "Forecast Accuracy for Seasonal Data",
      digits = array(4,ncol(biomass_scores))) %>%
  kable_styling(full_width = FALSE, position = "center") %>%
  #highlight model with lowest MAPE
  kable_styling(latex_options="striped", stripe_index = which.min(seas_scores[,"MAPE"]))
```







```{r}
# Model 1: Arithmetic mean
# The meanf() has no holdout option
MEAN_seas <- meanf(y = ts_biomass, h = 12)  
checkresiduals(MEAN_seas)
plot(MEAN_seas)


# Model 2: Seasonal naive
SNAIVE_seas <- snaive(ts_biomass, h=12, holdout=FALSE)
checkresiduals(SNAIVE_seas)
plot(SNAIVE_seas)


# Model 3: SARIMA

SARIMA_autofit <- auto.arima(ts_biomass)
checkresiduals(SARIMA_autofit)

#Generating forecasts
#remember auto.arima does not call the forecast() internally so we need one more step
SARIMA_for <- forecast(SARIMA_autofit,h=12)
plot(SARIMA_for)


# Model 4: SS Exponential smoothing
SSES_seas <- es(ts_biomass,model="ZZZ",h=12,holdout=FALSE)
plot(SSES_seas)
checkresiduals(SSES_seas)


# Model 5: SS with StructTS()

SS_seas <- StructTS(ts_biomass,
                    type="BSM",fixed=c(0,0.001,0.3,NA))   #this function has convergence issues
checkresiduals(SS_seas)

#Generating forecasts
# StructTS() does not call the forecast() internally so we need one more step
SS_for <- forecast(SS_seas,h=12)
plot(SS_for)



#Model 1: Arithmetic mean
MEAN_scores <- accuracy(MEAN_seas$mean,last_obs)  #store the performance metrics

#Model 2: Seasonal naive 
SNAIVE_scores <- accuracy(SNAIVE_seas$mean,last_obs)

# Model 3:  SARIMA 
SARIMA_scores <- accuracy(SARIMA_for$mean,last_obs)

# Model 4:  SSES
SSES_scores <- accuracy(SSES_seas$forecast,last_obs)

# Model 5:  BSM 
SS_scores <- accuracy(SS_for$mean,last_obs)


#create data frame
seas_scores <- as.data.frame(rbind(MEAN_scores, SNAIVE_scores, SARIMA_scores,SSES_scores,SS_scores))
row.names(seas_scores) <- c("MEAN", "SNAIVE","SARIMA","SSES","BSM")

#choose model with lowest RMSE
best_model_index <- which.min(seas_scores[,"RMSE"])
cat("The best model by RMSE is:", row.names(seas_scores[best_model_index,])) 


kbl(seas_scores, 
      caption = "Forecast Accuracy for Seasonal Data",
      digits = array(5,ncol(seas_scores))) %>%
  kable_styling(full_width = FALSE, position = "center") %>%
  #highlight model with lowest RMSE
  kable_styling(latex_options="striped", stripe_index = which.min(seas_scores[,"RMSE"]))



autoplot(ts_biomass_data) +
  autolayer(MEAN_seas, PI=FALSE, series="Mean") +
  autolayer(SNAIVE_seas, PI=FALSE, series="Naïve") +
  autolayer(SARIMA_for,PI=FALSE, series="SARIMA") +
  autolayer(SSES_seas$forecast, series="SSES") +
  autolayer(SS_for,PI=FALSE,series="BSM") + 
  xlab("Month") + ylab("Electricity Retail Price ($/kWh)") +
  guides(colour=guide_legend(title="Forecast"))



autoplot(ts_biomass_data) +

autolayer(SARIMA_for,PI=FALSE, series="SARIMA") +
  xlab("Month") + ylab("Total Biomass (g/m2)") +
  guides(colour=guide_legend(title="Forecast"))



# Forecast
SARIMA_autofit_new <- auto.arima(ts_biomass_data)
checkresiduals(SARIMA_autofit_new)

SARIMA_for_new <- forecast(SARIMA_autofit_new,h=12)
plot(SARIMA_for_new)



```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
