---
title: "Data process"
author: "Kassie"
output: html_document
date: "2023-04-07"
editor_options: 
  chunk_output_type: console
---

```{r packages}
library(dplyr)
library(lubridate)
library(zoo)
library()
library(readxl)
```

#run data wrangling and inspect the dataset
please!!
make sure the data wrangling file has properly produced the "ME_rawME_dayI.RDATA"
```{r packages}

load("ME_rawME_dayI.RDATA")

#inspect the product in data_wrangle
head(ME_rawME_dayI)
```

#generate monthly mean of biomass
```{r}
monthly_missing_data <- ME_rawME_dayI %>%
  mutate( Date = ymd(sampledate)) %>% 
  mutate( Year = year(Date), 
          Month = month(Date), 
          Day = day(Date)) %>%
  group_by( Year, Month ) %>%
  summarise(total_biomass_monthly = mean(total_biomass))
```

#generate a whole sequence for NA operations
```{r}
#create a full sequence of date
start_date <- ym("1995-01")
end_date <- ym("2020-12")

monthly_dates <- seq(from = start_date, to = end_date, by = "month") %>%
  as.data.frame() 
colnames(monthly_dates) <- c("date")

#inspect the dates
head(monthly_dates)

```

#plug in the data we've got
```{r}

#creating room for future variables
empty_full_df <- monthly_dates %>%
  mutate(Year = year(date), 
        Month = month(date),) %>%
  mutate(total_biomass=NA,
         TC=0, TN=0, TP=0)

biomass <- empty_full_df %>%
  left_join(monthly_missing_data,by=c("Year","Month")) %>%
  mutate(total_biomass=total_biomass_monthly) %>% 
  mutate(total_biomass=na.approx(total_biomass),rule=2) %>%
  dplyr::select(date,Year,Month,total_biomass)

#inspect the data
head(biomass)

```

#save final raw data
```{r}
save(biomass, file="biomass.RDATA")
```

#biomass+TNTP,Temperature
New dataset include T, TN, TP.

```{r}
load("ME_rawME_dayI.RDATA")

rawdata_all <- ME_rawME_dayI %>%
  mutate( date = ymd(sampledate)) %>% 
  mutate( Year = year(date), 
          Month = month(date), 
          Day = day(date)) %>%
  group_by( Year, Month ) %>%
  summarise('Biomass' = mean(total_biomass), 'TN' = mean(TN), 'TP' = mean(TP),'Temperature' = mean(Temperature)) %>% mutate(date = as.Date(paste(Year,Month, "01", sep = "-"), format = "%Y-%m-%d"))


start_date <- ym("1995-01")
end_date <- ym("2020-12")

monthly_dates <- seq(from = start_date, to = end_date, by = "month") %>%
  as.data.frame() 
colnames(monthly_dates) <- c("date")


rawdata_all <- right_join(rawdata_all,monthly_dates, by ='date' )


#fill the NA
# due to no T, TN, TP  before 1995-5-1, this all data also start at 1995-05-01
rawdata_all_fill <- rawdata_all[,c(7,6,4,5,3)] %>% arrange(date) %>% filter(!is.na(date)) %>% 
  filter(!date <= "1995-04-01" ) %>% mutate('Biomass'=na.approx(Biomass),rule=2)%>%
  mutate(Temperature =na.approx(Temperature),rule=2)%>%
  mutate(TN=na.approx(TN),rule=2)%>%
  mutate(TP=na.approx(TP),rule=2)


save(rawdata_all_fill, file="./Data/biomass_Env.RDATA")

```

